services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    volumes:
      - ./data:/app/data
    command: ["./myapp", "9090"]

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
    stdin_open: true
    tty: true
    command: ["python3", "Client.py", "server", "9090"]

  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests