services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    volumes:
      - ./data:/app/data
    environment:
      - MONGO_URI=mongodb://mongodb:27017/my_database_name
    command: ["./myapp", "9090"]
    depends_on:
      - mongodb

  webserver:
    build:
      context: .
      dockerfile: Dockerfile.webserver
    ports:
      - "3000:3000"
    depends_on:
      - server
    command: ["node", "app.js"]

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      # Ensure the C++ server starts before the Python client connects
      - server

  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
    depends_on:
      - server
      - mongodb

volumes:
  mongo-data: