FROM gcc:latest AS builder

RUN apt-get update && apt-get install -y cmake

COPY . /usr/src/myapp
WORKDIR /usr/src/myapp

RUN cmake -B build && cmake --build build

FROM gcc:latest AS server

COPY --from=builder /usr/src/myapp/build/myapp /app/myapp
COPY --from=builder /usr/src/myapp/data /app/data

WORKDIR /app
CMD ["./myapp"]