FROM node:18-slim AS react-builder
WORKDIR /app/react

COPY src/ex4-react/package*.json ./
RUN npm install

COPY src/ex4-react/ ./
RUN npm run build





FROM node:20-slim
WORKDIR /app

COPY src/EX3-NODEJS/package*.json ./
RUN npm install

COPY src/EX3-NODEJS/ ./

COPY --from=react-builder /app/react/build ./build

EXPOSE 3000
CMD ["node", "src/app.js"]